#!/usr/bin/env python
# plot e-fold colormap generated by efold_cmap-test.f90

#######################################################################

import numpy as np
from sys import argv
from astropy.io import fits

#######################################################################

# input files:
#   argv[1] -> text output from efold_cmap-test.f90 (default 'efold-cmap.dat')
#   argv[2] -> potential FITS file used by efold_cmap-test.f90 (default 'smpout.fits')
filename_efold = 'efold-cmap.dat' if len(argv) < 2 else argv[1]
filename_grf   = 'smpout.fits'    if len(argv) < 3 else argv[2]

# read e-fold grid from disk
# efold_cmap-test.f90 writes one row for each phi^2 index j and one column
# for each phi^1 index i, so the array can be passed directly to imshow.
efold = np.loadtxt(filename_efold, dtype=np.float64)

if efold.ndim != 2 or efold.shape[0] != efold.shape[1]:
    raise ValueError(f"Expected a square 2D e-fold grid, got shape {efold.shape}")

ny, nx = efold.shape

# read field-space bounds from the potential FITS file
with fits.open(filename_grf) as hdu:
    hdr = hdu[0].header
    lx = hdr['lx']
    ly = hdr['ly']

#######################################################################

import matplotlib.pyplot as plt

# Thicker axes
plt.rc('axes', linewidth=1)

# Use LaTeX for text rendering with default LaTeX math font (Computer Modern)
plt.rc('text', usetex=True)
plt.rc('font', size=10, family='serif', serif=['Computer Modern'])

# Plot parameters
# Use the same physical figure width as hex(1).py.
aspect    = 1.25
width     = 7.6
ax_left   = 0.125
ax_bottom = 0.18
ax_width  = 0.70
ax_height = 0.80

# Axes limits
phi1_min, phi1_max = -lx, lx
phi2_min, phi2_max = -ly, ly

fig = plt.figure(figsize=(width/2.54, width/aspect/2.54), frameon=False)
ax = fig.add_axes([ax_left, ax_bottom, ax_width, ax_height])
ax.set_aspect('equal', adjustable='box')
ax.set_box_aspect(1)

# efold_cmap-test.f90 uses the following sentinel values:
#   -1000 : V <= 0 excursion
#   +1000 : eternal-inflation candidate
# Genuine finite inflationary trajectories have 0 <= N <= N_max = 200.
N_max = np.max(efold[efold != 1E3])

# Values outside [0, N_max] are displayed using the under/over colors of
# the colormap, so the sentinel values do not compress the physical N scale.
cmap = plt.get_cmap('viridis').copy()
cmap.set_under('white')
cmap.set_over('tab:gray')
cmap.set_bad('black')

efold_plot = np.ma.masked_equal(efold, 0.0)

im = ax.imshow(
    efold_plot,
    extent=[-lx, lx, -ly, ly],
    origin='lower',
    vmin=0.0,
    vmax=N_max,
    cmap=cmap,
    interpolation='none'
)

# Same axis-label typography as plot-grf-res(1).py
ax.set_xlabel(r'$\phi^1 / M_{\mathrm{Pl}}$', fontsize=10)
ax.set_ylabel(r'$\phi^2 / M_{\mathrm{Pl}}$', fontsize=10)

ticks_x = np.linspace(int(phi1_min), int(phi1_max), 7)
ticks_y = np.linspace(int(phi2_min), int(phi2_max), 7)
ax.set_xticks(ticks_x)
ax.set_yticks(ticks_y)
ax.tick_params(axis='both', which='major', labelsize=8, length=2.5, width=1)

# Colorbar
cbar_gap    = 0.001
cbar_width  = 0.035
cbar_height = 0.80
cbar_bottom = 0.18
cax = fig.add_axes([ax_left + ax_width + cbar_gap, cbar_bottom, cbar_width, cbar_height])
cbar = fig.colorbar(im, cax=cax, extend='neither')
cbar.set_label(r'$N$', fontsize=10)
cbar.ax.tick_params(length=2.5, labelsize=8)

# Save figures
plt.savefig('efold-cmap-cnst.pdf')
plt.savefig('efold-cmap-cnst.png', dpi=500, transparent=False)

# show in interactive console
#plt.show()
